name: council-app

networks:
  otm-home:
    name: otm-home
    driver: bridge

services:
  otm-home-council:
    build:
      context: ..
      dockerfile: apps/council/Dockerfile
    container_name: otm-home-council
    ports:
      - "9001:9001"
    networks:
      - otm-home
    environment:
      OTM_HOME_COUNCIL_PORT: 9001,
      SSL_CERT_PATH: "/usr/local/share/ca-certificates/mint/server.crt"
      SSL_KEY_PATH: "/usr/local/share/ca-certificates/mint/server.key"
      NODE_ENV: production
      OLLAMA_HOST: http://otm-home-ollama:11434
    restart: unless-stopped
