name: otm-home-broker
networks:
  otm-home-raspi:
    name: otm-home-raspi
    driver: bridge
services:
  otm-home-kafka:
    image: ${KAFKA_IMAGE}
    container_name: otm-home-kafka
    ports:
      - 9092:9092
    volumes:
      - otm-home-kafka_data:/var/lib/kafka/data
    networks:
      - otm-home
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://otm-home-kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: PLAINTEXT_HOST
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    restart: always
